version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/go/src/github.com/TheGolurk/travis-test
hooks:
  BeforeInstall:
    - location: install.sh
  AfterInstall:
    - location: beforeinstall.sh
  ApplicationStart: 
    - location: runapp.sh
