version: 0.2

phases: 
  pre_build: 
    commands: 
      - "echo building..."
  build: 
    commands: 
      - "echo Build started on `date`"
      - "go build -o app"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "ls -al"
      - pwd

artifacts: 
  files: 
    - stop.sh
    - main.go
    - install.sh
    - runapp.sh
    - app
    - appspec.yml
    - buildspec.yml
