version: 0.2

run-as: root

env:
        variables:
                GOPATH: "/home/ubuntu/go"

phases:
             pre_build:
                commands:
                        - echo hola
             build:
                commands:
                        - sh runapp.sh
