version: 0.2

run-as: ubuntu

env:
        variables:
                GOPATH: "/home/ubuntu/go"

phases:
        build:
                run-as: ubuntu
                commands:
                        - sh runapp.sh
