version: 0.2

run-as: ubuntu

env:
        variables:
                GOPATH: "/home/ubuntu/go"

phases:
             pre_build:
                commands:
                        - pwd
                        - echo hola
             build:
                run-as: ubuntu
                commands:
                        - sh runapp.sh
