version: 0.2

run-as: ubuntu

env:
        variables:
                GOPATH: "/home/ubuntu/go"

phases:
        install:
                commands:
                        - echo install phase
                        - apt-get update -y
                finally:
                        - echo finally
        build:
                run-as: ubuntu
                commands:
                        - sh runapp.sh
