version: 0.2

run-as: ubuntu

env:
        variables:
                GOPATH: "/home/ubuntu/go"

phases:
         pre_build:
                     commands:
                        - echo Entered the pre_build phase...
                        - cd go/src/github.com/TheGolurk/travis-test
                     finally:
                        - echo This always runs even if the login command fails 
        build:
                run-as: ubuntu
                commands:
                        - sh runapp.sh
